variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/sustav-narucivanja/src'
  OUTPUT_PATH: '$CI_PROJECT_DIR/dist/angular-basic'

deploy:
  stage: deploy
  image: https://gitlab.com/null75/sustav-narucivanja
  script:
    - echo "App deployed successfully."